---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-8
    hostname: centos
    image: geerlingguy/docker-centos8-ansible:latest
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
  - name: ubuntu22-latest
    hostname: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible

