---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu22
    image: ubuntu:22.04
    command: ["/sbin/init"]
    pre_build_images:
      - docker://docker.io/library/ubuntu:22.04

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ubuntu22:
        ansible_connection: podman
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

scenario:
  name: podman
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - check
    - destroy

verifier:
  name: testinfra

lint: flake8